### ISSUE TITLE
RangeError (index): Invalid value: Valid value range is empty: 0

### ISSUE THREAD

**Issue by ashkryab** [desconexo/highlight_text#1]
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following RangeError was thrown building TextHighlight(dirty, state: _TextHighlightState#140ef):
RangeError (index): Invalid value: Valid value range is empty: 0
When the exception was thrown, this was the stack:
#0      List.[] (dart:core-patch/growable_array.dart:145:60)
#1      _TextHighlightState.build (package:highlight_text/src/TextHighlight.dart:51:34)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
#5      StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)

exception when move back on page with TextHighlight

my solve
![image](https://user-images.githubusercontent.com/26881635/60273443-d1c56300-98fe-11e9-91f0-41a7a1466448.png)

**Comment by desconexo** [comment]
Hi, thanks for the support.
