### ISSUE TITLE
RangeError (index): Invalid value: Valid value range is empty: -1

### ISSUE THREAD

**Issue by BSid96** [desconexo/highlight_text#10]
Having a space at the end of the string ( for example "This is a string " ) throws RangeError (index): Invalid value: Valid value range is empty: -1. Removing the space ( for example "This is a string" ) fixes the problem. There might be a problem in the way string is parsed

**Comment by desconexo** [comment]
Hi, I'm currently reworking this package and this problem it's not happening anymore. Soon i'll upload it
