### ISSUE TITLE
Background and backgroundColor does not work as expected

### ISSUE THREAD

**Issue by cenkingunlugu** [desconexo/highlight_text#11]
Problematic Widget: HighlightedWord

If I use a text:

"I had some aggression then
In the airport someone was there"

If I give a map of HighlightedWord with TextStyle including:

backgroundColor: Colors.red
or
background: Paint()
                ..strokeWidth = 10.0
                ..color = Colors.red
                ..style = PaintingStyle.stroke
                ..strokeJoin = StrokeJoin.round

What I expect to see is the only the background of my keys should be red.

But my background starts from the first key, ends at the end of the text.

**Comment by desconexo** [comment]
Hi, I'm reworking this package but I couldn't fix this problem yet. I don't know why, but you need to revert this background in TextHighlight's textStyle.

Something like:
TextHighlight(
    text: text,
    words: words,
    textStyle: TextStyle(
    fontSize: 20.0,
    color: Colors.black,
    background: Paint()
        ..strokeWidth = 0
        ..color = Colors.transparent,
    ),
    textAlign: TextAlign.justify,
),
