### ISSUE TITLE
RangeError 

### ISSUE THREAD

**Issue by sjsam** [desconexo/highlight_text#14]
Lines 74,75 in highlight_text.dart,
```
 int strIndex = bindedText.toLowerCase().indexOf(word.toLowerCase());
 bindedText = bindedText.replaceRange(strIndex, strIndex + word.length,
            '<highlight>${words.keys.toList().indexOf(word)}<highlight>');
```
throws an instance of  'RangeError' when the 'word.toLowerCase()' is not found in 'bindedText.toLowerCase()' whereby 'strIndex' is set to -1. A condition is missing here?
```
int strIndex = bindedText.toLowerCase().indexOf(word.toLowerCase());
if(strIndex>=0) {
 bindedText = bindedText.replaceRange(strIndex, strIndex + word.length,
            '<highlight>${words.keys.toList().indexOf(word)}<highlight>');
}
```

**Comment by desconexo** [comment]
Hi, can you send me the text and words you used?

**Comment by sjsam** [comment]
text - 

`FLOOR COVERINGS OF PLASTICS, WHETHER OR NOT SELF - ADHESIVE, IN ROLLS OR IN THE FORM OF TILES; WALL OR CEILING COVERINGS OF PLASTICS, AS DEFINED IN NOTE 9 TO THIS CHAPTER - OF OTHER PLASTICS :WALL OR CEILING COVERINGS COMBINED WITH KNITTED OR WOVEN FABRIC`

words - 
`[CLOTH,FABRIC]`

and below is the piece of code:

```
TextHighlight(
text: '${description}',
words: highlightedWords,
textStyle: textStyle1.copyWith(
  backgroundColor: WHITE),
textAlign: TextAlign.left,
enableCaseSensitive: false,
)
```

**Comment by desconexo** [comment]
I was able to reproduce, thank you. I'll fix that soon.

**Comment by sjsam** [comment]
There  `RangeError` even if I put the `enableCaseSensitive: true`. However, I am not able to reproduce it.

**Comment by desconexo** [comment]
Fixed. Sorry that I take so long to fix something like this. I was busy and ended up forgetting about it

**Comment by sjsam** [comment]
No issues, thanks. I saw the package upgrade in pub and understood that you fixed it.
