### ISSUE TITLE
First word in text not matching 

### ISSUE THREAD

**Issue by mamirix** [desconexo/highlight_text#15]
it's not matching for first word in text
<img width="247" alt="Screen Shot 2021-09-01 at 4 32 38 PM" src="https://user-images.githubusercontent.com/6995719/131680555-8614913e-ada8-4cc9-8bd7-2b46d81f5420.png">
. I believe the error is caused  by the statement in line 80 in highlight_text.dart. strIndex should be compared to ">= 0"

 if (strIndex > 0)
          bindedText = bindedText.replaceRange(strIndex, strIndex + word.length,
              '<highlight>${words.keys.toList().indexOf(word)}<highlight>');

**Comment by desconexo** [comment]
"Mohib" is different than "mohib", so you must use enableCaseSensitive: true to work like you want. If you're already using enableCaseSensitive: true then it's a bug and I'll work on it tonight. Thank you.

**Comment by desconexo** [comment]
https://github.com/desconexo/highlight_text#100-breaking-changes

**Comment by desconexo** [comment]
Actually, you must use enableCaseSensitive: false (its default value is false). I now it's confusing, I'll rework this in the next update.

**Comment by desconexo** [comment]
Yes, you're right. The problem is the if statement
