### ISSUE TITLE
How to ignore case put paint original world

### ISSUE THREAD

**Issue by paulo-coutinho** [desconexo/highlight_text#16]
Hi,

I want paint all words, ignoring case, but without change the "original word".

Im highlight word "JeSuS", but when i use "enableCaseSensitive: false" it highlight the word changing their original case too.

Im searching for "JeSuS" and it change original words "JESUS" and "Jesus" for "JeSuS" too.

![image](https://user-images.githubusercontent.com/395096/134768522-1852b98f-dbdf-441d-87e1-09165a00cb98.png)

Can you make some variable to keep original case and only highlight the word?

Thanks.

**Comment by desconexo** [comment]
Hi, can you send me the whole text and the words you're highlighting, please?

**Comment by desconexo** [comment]
Oh, I get it. I'll work on it, thank you.

**Comment by desconexo** [comment]
Fixed it. You'll need to use matchCase instead of enabledCaseSensitive, I renamed it to be clearer
