### ISSUE TITLE
First word in text is raised

### ISSUE THREAD

**Issue by timmydan** [desconexo/highlight_text#17]
If the first word in the text is marked for highlighting, it is raised above the level of the following text. The only way I have found to partially resolve this is to add a " " before the text, but that causes a problem for left-aligning it. For example:

```dart
TextHighlight(
                text: "Testing the height of the first word", 
                words: highlightedWords as LinkedHashMap<String, HighlightedWord>,
                textStyle: TextStyle(
                    fontFamily: chosenFont,
                    color: color,
                    fontSize: fontSize,
                ),
                textAlign: TextAlign.left,
              )

highlightedWords = {};
String wordToAdd = "testing";

highlightedWords[wordToAdd] =
          HighlightedWord(
              onTap: () {
                setState(() {
                  action;
                });
              },
              textStyle: highlightTextStyle,
              decoration: highlightDecoration
          );
```

Results in:
<img width="324" alt="Screenshot 2021-10-11 at 16 03 07" src="https://user-images.githubusercontent.com/14905268/136766544-6e6c09f2-d655-41a5-91fd-2a991f121077.png">

As you can see, I'm also having trouble with the `matchCase: false` setting too, but that's a different issue.

Thanks for making this by the way. I'm finding it useful!

**Comment by timmydan** [comment]
I found one of the problems that could be a quick fix, but it's to do with matchCase rather than my original word height question.
On line 105, the ? and : blocks are backwards. Currently they are:
```dart
String showWord = matchCase ?  originalWords[currentWord]! : currentWord;
```
but should be:
```dart
String showWord = matchCase ? currentWord : originalWords[currentWord]!;
```
The originalWords Map is only filled in when matchCase is false, so it should only be accessed when matchCase is false.

**Comment by desconexo** [comment]
[This comment](https://github.com/desconexo/highlight_text/issues/17#issuecomment-939997531) is right, I messed up when I wrote it.
Which version are you using? I've created a new project and imported the package from git, your example above worked fine.

**Comment by Mehedi50200** [comment]
Still facing this issue. Highlighted text is miss-aligning slightly to the top. More visible in IOS.

**Comment by djsamseng** [comment]
Note I was able to get around this issue by using `highlightBuilder`

```dart
return TextHighlight(
   text: text, 
   words: highlights, 
   textStyle: Theme.of(context).textTheme.headlineMedium, 
   highlightBuilder: (fullText, highlightText, highlightStyle) {
      return TextSpan(text: highlightText, style: highlightStyle);
   },
);
```
