### ISSUE TITLE
[Feature Request] Highlight all occurances of a word, not only the first one

### ISSUE THREAD

**Issue by ThorgeL** [desconexo/highlight_text#18]
I am not sure if this is on purpose or not. I would love to use this dependency but I need to highlight every occurrence of a given word in the text and not only the first one.

**Comment by desconexo** [comment]
Done.

I added 'bindind' parameter to TextHighlight, now you can choose HighlightBinding.all (highlights all the occurrences), HighlightBinding.first (highlights only the first occurrence) or HighlightBinding.last (highlights only the last ocurrence).

Thank you.
