### ISSUE TITLE
last word in string

### ISSUE THREAD

**Issue by ashkryab** [desconexo/highlight_text#2]
If the highlighted word is the last in the string it is not highlighted.
example:
**word** **word** **word** **word** word

**Comment by ashkryab** [comment]
without a dot in the end

**Comment by desconexo** [comment]
yeah, i'm working on it right now

**Comment by desconexo** [comment]
I was so confused that I just remade it. It's fine, I think.
Uploading soon as possible.

**Comment by desconexo** [comment]
done
