### ISSUE TITLE
matchCase not working if false

### ISSUE THREAD

**Issue by lauraldo** [desconexo/highlight_text#24]
Text not matching pattern by case is not highlighted.

In `highlight_text.dart`, line 96, loop condition contains `word.allMatches(text).length`, which is case-sensitive.

**Comment by desconexo** [comment]
can you send me the text and words you're trying to highlight, please?

**Comment by lauraldo** [comment]
Text: "Security"
Words: {"sec"}

**Comment by desconexo** [comment]
The package only works with words, so it do not support what you're trying to do.

**Comment by desconexo** [comment]
That's new for me. I didn't know it would work like that. I'll try to fix it this weekend.

**Comment by desconexo** [comment]
Actually, I just fixed it. But I'm not able to upload it to pub.dev any soon, so you'll need to import it from github

**Comment by lauraldo** [comment]
Great, thanks a lot!
