### ISSUE TITLE
Multiple Highlight

### ISSUE THREAD

**Issue by Bockey1999** [desconexo/highlight_text#28]
I'm trying to highlight one specific occurrence of a word and it highlighting it where it shows up in the text.

eg.
"This is **an** sad day. I want **an** icecream **an**d sauce."

Should I do this it will highlight this when I only wanted the second an.

**Comment by desconexo** [comment]
I believe this is not possible with this package.
For the above sentence you should add `matchCase: true` and `binding: HighlightBinding.last` to `TextHighlight` widget. But it will only work for this especific text.
