### ISSUE TITLE
Highlighted words are raised

### ISSUE THREAD

**Issue by crizant** [desconexo/highlight_text#33]
<img width="124" alt="Screen Shot 2022-09-20 at 11 47 29 AM" src="https://user-images.githubusercontent.com/8337876/191163201-77e87261-0e7a-4284-bd3d-5be0042cb44e.png">
Maybe we should add `alignment: PlaceholderAlignment.middle` to the `WidgetSpan`?

**Comment by crizant** [comment]
In my own fork I changed `WidgetSpan` to `TextSpan` to fix vertical alignments, but in that case we can't add decoration and padding to the keywords:
```
return TextSpan(
    children: [
      TextSpan(
        text: showWord,
        style: words[currentWord]!.textStyle ?? textStyle,
        recognizer: TapGestureRecognizer()
          ..onTap = words[currentWord]!.onTap ?? () {},
      ),
      _buildSpan(boundWords),
    ],
  );
```

**Comment by lauraldo** [comment]
@crizant so where can I find your fork?

**Comment by crizant** [comment]
> @crizant so where can I find your fork?

It’s in my working account. I made it at work so technically it’s not okay to share it publicly.
Maybe you should make your own, the core change is in my previous comments.

**Comment by desconexo** [comment]
thank you. I cannot remove WidgetSpan, but I added a new argument to TextHighlight named spanAlignment, that you can set it to PlaceholderAlignment.middle
