### ISSUE TITLE
The highlighted text takes full line if it spans to the next line

### ISSUE THREAD

**Issue by jonnyjohnson1** [desconexo/highlight_text#47]
<img width="360" alt="Screenshot 2023-06-23 at 9 44 38 AM" src="https://github.com/desconexo/highlight_text/assets/32085184/1164ebce-1620-4f8a-9732-733dd42f6ce0">

The highlighted text takes the full line if it spans to the next line. See above.

I think the issue is within the WidgetSpan class. I'm playing with it now, but haven't found a solution.

**Comment by jonnyjohnson1** [comment]
The widget span places a widget between widgets. As long as the size of the inserted widget fits within a single row of text, it can all fit on one row, but if its size goes past a row, then the widget span starts and ends on its own full rows. 

This may work for a lot of people, but more work has to be done to make the use of the widget span a solution for this case of highlighted text.

**Comment by desconexo** [comment]
Hi. I have no plans to work on this any soon, but this case can probrably be fixed using "splitOnLongWord: true" on TextHighlight. I don't know if that's what you need, but maybe work.

**Comment by jonnyjohnson1** [comment]
Thanks. I'll try it.
