### ISSUE TITLE
Empty text cause error

### ISSUE THREAD

**Issue by hasimyerlikaya** [desconexo/highlight_text#6]
Hi, thank you for this package.
I try to use this package. I found an error.
If currentWord is empty, that line cause error.

String charLastRemoved = currentWord[currentWord.length - 1];

**Comment by desconexo** [comment]
@hasimyerlikaya can you give me the steps to reproduce it? What phrase and dictionary did you used?

**Comment by Janghwi** [comment]
Thank you for your excellent function. 
Could you expand a function containing string itself. For example, Phrases search function,,, "Flutter seems" like this style.
