### ISSUE TITLE
Not working with numbers

### ISSUE THREAD

**Issue by fenchai23** [desconexo/highlight_text#8]
String needle = '22020 toy 4x4 combo';

    String haystack = '17801-22020 TOY RAV4 COMBO 4x4';

    List<String> needleList = needle.split(' ');

    Map<String, HighlightedWord> testWords = {
      for (var v in needleList)
        v: HighlightedWord(
            textStyle: TextStyle(color: Colors.red), onTap: () {})
    };

the **22020** does not get highlighted sadly Is this a limitation? :(

edit: 17801-22020 (works), -22020 (does not work), rav (works), so this is more like a limitation of IF  it contains numbers then it needs to match the entire word?

**Comment by desconexo** [comment]
Hi, I'm currently reworking this package and this problem it's not happening anymore. Soon i'll upload it
